Bump CoreMods version. (#426)
Update CoreMods version to 6.0.4 which uses the new SPI artifact.
This fixes the duplicate SPI dependencies which caused a
`NoClassDefFoundError` in certain situations.